In [15]:
import pandas as pd

news = pd.read_excel("COIN_sent.xlsx", header=3, index_col=0)
news

,TWITTER_SENTIMENT_DAILY_AVG,TWITTER_PUBLICATION_COUNT,TWITTER_NEG_SENTIMENT_COUNT,TWITTER_POS_SENTIMENT_COUNT,TWITTER_SENTIMENT_DAILY_MAX,TWITTER_NEUTRAL_SENTIMENT_CNT,TWITTER_SENTIMENT_DAILY_MIN,NEWS_SENTIMENT_DAILY_AVG
Dates,,,,,,,,
2021-04-01,0.0032,10,1,1,0.1068,14,-0.1068,-0.6321
2021-04-02,0.0019,174,2,8,0.1068,169,-0.1068,0.0005
2021-04-05,0.0025,41,1,2,0.1070,34,0.0000,0.0000
2021-04-06,0.0277,85,2,11,0.3479,69,-0.1068,0.0000
2021-04-07,0.0900,353,8,80,0.8619,247,-0.0863,0.1286
...,...,...,...,...,...,...,...,...
2024-03-26,0.0261,733,5,30,0.4438,173,-0.1830,0.1753
2024-03-27,-0.0049,502,12,7,0.4438,145,-0.1830,0.0113
2024-03-28,-0.1393,955,148,22,0.4438,348,-0.1830,-0.5112
2024-03-29,-0.0236,470,22,8,0.4438,128,-0.1830,-0.0477
2024-04-01,-0.0144,210,9,7,0.4438,71,-0.1830,-0.0031

In [16]:
type(news.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [17]:
full_date_range = pd.date_range(start=news.index.min(), end=news.index.max())
news = news.reindex(full_date_range)

In [18]:
news.ffill(inplace=True)

In [19]:
news = news.shift(1)
news.dropna(inplace=True)

In [20]:
news.to_csv("../Data/BB_sentiment_lag1.csv")